name: "release-api"

on:
  push:
    tags:
      - "APIv*"
jobs:
  release-api:
    name: "API Automatic release"
    runs-on: "ubuntu-latest"
    steps:
    - name: "Releae"
      run: |
        echo "Prepairing realse"

    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.1.0
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          public
          routes
          src
          Dockerfile
          README.md
          index.js
          package.json
